CREATE DATABASE CLOUDSTORE;
USE CLOUDSTORE;

CREATE TABLE PRODUCT (
	ID BIGINT AUTO_INCREMENT NOT NULL,
	PRODUCT_NAME VARCHAR(255),
	PRIMARY KEY (ID)
) ENGINE=INNODB;

CREATE TABLE CATEGORY (
	ID BIGINT AUTO_INCREMENT NOT NULL,
	CATEGORY_NAME VARCHAR(255),
	PARENT_ID BIGINT,
	PRIMARY KEY (ID)
) ENGINE=INNODB;

CREATE TABLE CATEGORY_PRODUCT (
	CATEGORY_ID BIGINT NOT NULL,
	PRODUCT_ID BIGINT NOT NULL,
	CONSTRAINT FK_CATEGORY_PRODUCT FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID),
	CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
) ENGINE=INNODB;
